export type StockItem = {
  name: string;
  zh: string;
  cat: string;
  qty: number;
  where: string;
  added: string;
};

export const STOCK: StockItem[] = [
  { name: "Broccoli", zh: "花椰菜", cat: "Vegetable", qty: 2, where: "Fridge", added: "Today" },
  { name: "Beef sirloin", zh: "牛肉", cat: "Protein", qty: 1, where: "Fridge", added: "Today" },
  { name: "Green onion", zh: "青蔥", cat: "Vegetable", qty: 4, where: "Fridge", added: "Today" },
  { name: "Tomato", zh: "番茄", cat: "Vegetable", qty: 3, where: "Fridge", added: "Today" },
  { name: "Avocado", zh: "酪梨", cat: "Fruit", qty: 1, where: "Counter", added: "Today" },
  { name: "Garlic", zh: "蒜頭", cat: "Aromatic", qty: 1, where: "Pantry", added: "3 days ago" },
  { name: "Eggs", zh: "雞蛋", cat: "Protein", qty: 6, where: "Fridge", added: "3 days ago" },
  { name: "Onion", zh: "洋蔥", cat: "Vegetable", qty: 2, where: "Pantry", added: "1 week ago" },
  { name: "Soy sauce", zh: "醬油", cat: "Pantry", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Rice", zh: "白米", cat: "Pantry", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Salt", zh: "鹽", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Sugar", zh: "糖", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Black pepper", zh: "黑胡椒", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "White pepper", zh: "白胡椒", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Cooking oil", zh: "食用油", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Sesame oil", zh: "香油", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Cornstarch", zh: "太白粉", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" },
  { name: "Rice wine", zh: "米酒", cat: "Condiment", qty: 1, where: "Pantry", added: "1 month ago" }
];

/* Category filter keys shared by Browse and Recipes. */
export const DISH_FILTER_KEYS = [
  "All", "Stir-fry", "Rice bowl", "Side", "Beef", "Chicken", "Pork", "Lamb", "Goat",
  "Seafood", "Pasta", "Dessert", "Breakfast", "Starter", "Vegetarian", "Vegan", "Miscellaneous"
] as const;

/* No source gives us a real prep/cook time, so this estimates one from what we do
   have: category (a proxy for cooking method — a stir-fry moves faster than a
   braise or a bake) and ingredient count (a proxy for prep work). Rounded to the
   nearest 5 minutes so it reads as an estimate, not a measurement. */
const CATEGORY_BASE_MINUTES: Record<string, number> = {
  "Stir-fry": 15, "Rice bowl": 20, Side: 15, Starter: 20, Salad: 15,
  Chicken: 30, Seafood: 20, Pasta: 20, Vegetarian: 20, Vegan: 20,
  Beef: 35, Pork: 35, Lamb: 40, Goat: 45,
  Breakfast: 20, Dessert: 40, Miscellaneous: 25
};

export function estimateMinutes(ing: [string, string, string][], cat: string): number {
  const base = CATEGORY_BASE_MINUTES[cat] ?? 25;
  const prep = Math.max(0, ing.length - 4) * 2;
  return Math.round((base + prep) / 5) * 5;
}

/* Each press of Capture reveals the next frame: the items that shot picks up. */
export const SHOTS: { items: [string, number][]; boxes: [string, string, string, string, string, string][] }[] = [
  { items: [["Broccoli", 1], ["Beef sirloin", 1]], boxes: [["Broccoli", "14%", "22%", "26%", "34%", "var(--color-accent)"], ["Beef sirloin", "56%", "44%", "26%", "30%", "var(--color-accent-2)"]] },
  { items: [["Green onion", 3]], boxes: [["Green onion", "20%", "50%", "34%", "22%", "var(--color-accent)"]] },
  { items: [["Tomato", 2], ["Avocado", 1]], boxes: [["Tomato", "12%", "26%", "22%", "30%", "var(--color-accent)"], ["Avocado", "48%", "36%", "22%", "28%", "var(--color-accent-2)"]] },
  { items: [["Tomato", 1], ["Garlic", 1]], boxes: [["Garlic", "34%", "30%", "24%", "26%", "var(--color-accent-2)"]] }
];

export const ITEMS: Record<string, { zh: string; cat: string; conf: number; unit: string }> = {
  Broccoli: { zh: "花椰菜", cat: "Vegetable", conf: 98, unit: "heads" },
  "Beef sirloin": { zh: "牛肉", cat: "Protein", conf: 94, unit: "packs" },
  "Green onion": { zh: "青蔥", cat: "Vegetable", conf: 96, unit: "stalks" },
  Tomato: { zh: "番茄", cat: "Vegetable", conf: 99, unit: "pieces" },
  Avocado: { zh: "酪梨", cat: "Fruit", conf: 91, unit: "pieces" },
  Garlic: { zh: "蒜頭", cat: "Aromatic", conf: 88, unit: "bulbs" }
};

/* Stand-in photography from TheMealDB (themealdb.com) — ingredient cut-outs by name,
   dish shots by id. Swap for your own photography when you have it. */
export const ING_IMG: Record<string, string> = {
  Broccoli: "Broccoli", "Beef sirloin": "Beef", "Green onion": "Spring Onions",
  Tomato: "Tomato", Avocado: "Avocado", Garlic: "Garlic", Eggs: "Egg", Rice: "Rice"
};

export const DISH_IMG: Record<string, string> = {
  "beef-broccoli": "m0p0j81765568742.jpg",
  "tomato-egg": "rwvw8q1765660071.jpg",
  "egg-foo-young": "47y6ii1765658818.jpg",
  "basil-chicken": "el64dy1763483009.jpg",
  "banh-mi-bowl": "z0ageb1583189517.jpg",
  "garlic-broccoli": "",
  "algerian-kefta-meatballs": "8rfd4q1764112993.jpg",
  "arepa-pabellon": "13fg4j1764441982.jpg",
  "arepa-pelua": "jgl9qq1764437635.jpg",
  "asado": "kgfh3q1763075438.jpg",
  "aussie-burgers": "44bzep1761848278.jpg",
  "barbados-pepperpot": "5tf8j11782236249.jpg",
  "beef-and-mustard-pie": "sytuqu1511553755.jpg",
  "beef-and-oyster-pie": "wrssvt1511556563.jpg",
  "beef-asado": "pkopc31683207947.jpg",
  "15-minute-chicken-and-halloumi-burgers": "vdwloy1713225718.jpg",
  "ayam-percik": "020z181619788503.jpg",
  "belgian-waterzooi-chicken": "nmxec11782498644.jpg",
  "bengali-chicken-curry-with-potatoes": "9ya6o71780262651.jpg",
  "brown-stew-chicken": "sypxpx1515365095.jpg",
  "chick-fil-a-sandwich": "sbx7n71587673021.jpg",
  "chicken-and-chorizo-rice-pot": "fk80jp1763280767.jpg",
  "chicken-and-mushroom-hotpot": "uuuspp1511297945.jpg",
  "chicken-alfredo-primavera": "syqypv1486981727.jpg",
  "chicken-and-potato-roti": "mp9z0i1782238092.jpg",
  "bleskiver": "wkhg581762773124.jpg",
  "alfajores": "a4kgf21763075288.jpg",
  "anzac-biscuits": "q47rkb1762324620.jpg",
  "apam-balik": "adxcbq1619787919.jpg",
  "apple-and-blackberry-crumble": "xvsurr1511719182.jpg",
  "apple-cake": "c0gmo31766594751.jpg",
  "apple-frangipan-tart": "wxywrq1468235067.jpg",
  "apple-pie": "stnxzp1784835840.jpg",
  "apple-pie-pops": "ax643t1784731109.jpg",
  "apricot-and-turkish-delight-mess": "p277uc1764109195.jpg",
  "adana-kebab": "04axct1763793018.jpg",
  "chilli-ginger-lamb-chops": "8xuvhj1763794991.jpg",
  "chorba-hamra-bel-frik-algerian-lamb-tomato-and-freekeh-soup": "p9tebp1764118792.jpg",
  "farikal-norwegian-national-dish": "ttfxxn1762773067.jpg",
  "hot-cumin-lamb-wrap-with-crunchy-slaw-and-spicy-mayo": "jyylmo1763790808.jpg",
  "imam-bayildi-with-bbq-lamb-and-tzatziki": "ampz9v1763787134.jpg",
  "kapsalon": "sxysrt1468240488.jpg",
  "kelem-dolmasi": "7vdtqi1780160088.jpg",
  "keleya-zaara": "8x09hy1560460923.jpg",
  "kofta-burgers": "lgmnff1763789847.jpg",
  "achiote-oil-aceite-achiotado-recipe": "iuws3q1783801530.jpg",
  "aji-de-aguacate-recipe-colombian-spicy-avocado-sauce": "jyvy8u1783800448.jpg",
  "bean-and-sausage-hotpot": "vxuyrx1511302687.jpg",
  "bolita-di-keshi": "skzd0x1780091674.jpg",
  "callaloo-jamaican-style": "ussyxw1515364536.jpg",
  "chakchouka": "gpz67p1560458984.jpg",
  "clear-soup-with-semolina-dumplings": "qserum1780156275.jpg",
  "duck-confit": "wvpvsu1511786158.jpg",
  "french-lentils-with-garlic-and-thyme": "vwwspt1487394060.jpg",
  "french-omelette": "yvpuuy1511797244.jpg",
  "chilli-prawn-linguine": "usywpp1511189717.jpg",
  "fettuccine-alfredo": "0jv5gx1661040802.jpg",
  "fettucine-alfredo": "uquqtu1511178042.jpg",
  "grilled-mac-and-cheese-sandwich": "xutquv1505330523.jpg",
  "lasagna-sandwiches": "xr0n4r1576788363.jpg",
  "lasagne": "wtsvxx1511296896.jpg",
  "macaroni-pie": "kpiu4t1782242131.jpg",
  "macaroni-pudding": "hbte551782770868.jpg",
  "pilchard-puttanesca": "vvtvtr1511180578.jpg",
  "spaghetti-alla-carbonara": "llcbn01574260722.jpg",
  "bubble-and-squeak": "xusqvw1511638311.jpg",
  "arroz-al-horno-baked-rice": "qt4i0n1763256454.jpg",
  "bai-sach-chrouk-grilled-pork-with-rice": "f0cdwk1782688162.jpg",
  "barbecue-pork-buns": "tzsy461763769901.jpg",
  "bbq-pork-sloppy-joes": "atd5sh1583188467.jpg",
  "belgian-stoemp": "byolko1782500400.jpg",
  "bigos-hunters-stew": "md8w601593348504.jpg",
  "boxty-breakfast": "naqyel1608588563.jpg",
  "bryndzove-halusky": "g33c901763365484.jpg",
  "cambodian-stir-fried-morning-glory-with-pork-fermented-soybeans-and-garlic": "wympxc1779734808.jpg",
  "acaraje-black-eyed-pea-fritters-with-shrimp-filling": "dxs5t71782678369.jpg",
  "amok-trey-cambodian-fish-curry": "diuub11782687570.jpg",
  "arroz-con-gambas-y-calamar": "jc6oub1763196663.jpg",
  "bahia-style-moqueca-prawn-stew": "e2kcut1782591669.jpg",
  "baked-salmon-with-fennel-and-tomatoes": "1548772327.jpg",
  "balchi-di-pisca": "qqwhw51780093126.jpg",
  "bang-bang-prawn-salad": "4xcfai1763765676.jpg",
  "bangladeshi-fish-curry-with-daikon": "r7mcjm1780261264.jpg",
  "barramundi-with-moroccan-spices": "4o4wh11761848573.jpg",
  "cajun-spiced-fish-tacos": "uvuyxu1503067369.jpg",
  "air-fryer-egg-rolls": "grhn401765687086.jpg",
  "algerian-bouzgene-berber-bread-with-roasted-pepper-sauce": "se5vhk1764114880.jpg",
  "algerian-carrots": "o2cd4r1764113576.jpg",
  "almojabanas-colombian-cheese-bread": "ymk7gt1783803106.jpg",
  "apple-potato-mash-hete-bliksem": "pa03n41777540582.jpg",
  "arepa": "ejht7k1780092390.jpg",
  "baba-ghanoush": "dlmh401760524897.jpg",
  "bajan-salt-bread-recipe": "sr7chd1780264758.jpg",
  "bajan-sweet-bread": "5vhbzt1782239221.jpg",
  "baked-yuca-fries": "j223gc1784579841.jpg",
  "ajo-blanco": "5jdtie1763289302.jpg",
  "baked-brie-with-sorrel-jam": "fg7d641784666908.jpg",
  "black-bean-soup": "x0mreq1784577446.jpg",
  "broccoli-and-stilton-soup": "tvvxpv1511191952.jpg",
  "clam-chowder": "rvtvuw1511190488.jpg",
  "colombian-style-stuffed-potatoes": "zdyurx1783801146.jpg",
  "cream-cheese-tart": "wurrux1468416624.jpg",
  "creamy-tomato-soup": "stpuws1511191310.jpg",
  "dominican-bakes": "cbfy1c1784672521.jpg",
  "mantu-afghan-dumpling": "oemdp11779556068.jpg",
  "fasoliyyeh-bi-z-zayt-syrian-green-beans-with-olive-oil": "21yc5s1760524759.jpg",
  "padron-peppers": "0ljvc51763248075.jpg",
  "red-onion-pickle": "ppodrp1762325183.jpg",
  "roast-fennel-and-aubergine-paella": "1520081754.jpg",
  "vegan-banh-mi": "sonirb1763782831.jpg",
  "vegan-chocolate-cake": "qxutws1486978099.jpg",
  "vegan-lasagna": "rvxxuy1468312893.jpg",
  "air-fryer-patatas-bravas": "3m8yae1763257951.jpg",
  "algerian-flafla-bell-pepper-salad": "tbj1bs1764118062.jpg",
  "aubergine-and-hummus-grills": "zub3s91764110535.jpg",
  "aubergine-couscous-salad": "02s6gc1763799560.jpg",
  "avocado-dip-with-new-potatoes": "flrajf1762341295.jpg",
  "baingan-bharta": "urtpqw1487341253.jpg",
  "beetroot-and-red-cabbage-sauerkraut": "ra2k8a1764365055.jpg",
  "beetroot-latkes": "qwicc91764368097.jpg",
  "beetroot-soup-borscht": "zadvgb1699012544.jpg",
  "black-beans-hotpot": "81ahfr1784394567.jpg",
  "antiguan-breakfast-chop-up-and-saltfish": "jvjnoh1780086318.jpg",
  "bread-omelette": "hqaejl1695738653.jpg",
  "breakfast-potatoes": "1550441882.jpg",
  "dutch-poffertjes-mini-pancakes": "oaqz9f1766593912.jpg",
  "english-breakfast": "utxryw1511721587.jpg",
  "flija-layered-pancake-crepe": "eqnf3p1779649407.jpg",
  "fruit-and-cream-cheese-breakfast-pastries": "1543774956.jpg",
  "full-english-breakfast": "sqrtwu1511721265.jpg",
  "grits": "bfok4w1780242078.jpg",
  "home-made-mandazi": "thazgm1555350962.jpg",
  "jamaican-curry-goat": "uc9qp11764796575.jpg",
  "mbuzi-choma-roasted-goat": "cuio7s1555492979.jpg",
};

export const ingImg = (name: string) =>
  "https://www.themealdb.com/images/ingredients/" + encodeURIComponent(ING_IMG[name] || name) + ".png";

export const dishImg = (id: string) =>
  DISH_IMG[id] ? "https://www.themealdb.com/images/media/meals/" + DISH_IMG[id] : ingImg("Broccoli");

export type Dish = {
  id: string;
  mealId: string;
  name: string;
  zh: string;
  cat: string;
  ing: [string, string, string][];
};

/* Real recipes from TheMealDB — mealId drives the live lookup; the seed ingredient
   list below is what shows until the fetch lands. */
export const DISHES: Dish[] = [
  { id: "beef-broccoli", mealId: "53366", name: "Beef and broccoli stir-fry", zh: "蔥爆牛肉花椰菜", cat: "Stir-fry",
    ing: [["Sirloin steak", "牛肉", "1 lb"], ["Broccoli", "花椰菜", "1 lb"], ["Soy Sauce", "醬油", "1 tbsp"], ["Oyster Sauce", "蠔油", "2 tbsp"], ["Garlic", "蒜頭", "2 cloves"]] },
  { id: "tomato-egg", mealId: "53372", name: "Chinese tomato egg stir-fry", zh: "番茄炒蛋", cat: "Stir-fry",
    ing: [["Plum Tomatoes", "番茄", "1 lb"], ["Eggs", "雞蛋", "5"], ["Spring Onions", "青蔥", "1"], ["Jasmine Rice", "白米", "2 cups"]] },
  { id: "egg-foo-young", mealId: "53370", name: "Egg foo young", zh: "芙蓉蛋", cat: "Stir-fry",
    ing: [["Egg", "雞蛋", "8"], ["Shrimp", "蝦仁", "20"], ["Spring Onions", "青蔥", "1"], ["Soy Sauce", "醬油", "1 tbsp"], ["Oyster Sauce", "蠔油", "1 tbsp"], ["Jasmine Rice", "白米", "2 cups"]] },
  { id: "basil-chicken", mealId: "53201", name: "Stir-fried chicken with chillies & basil", zh: "打拋雞", cat: "Stir-fry",
    ing: [["Chicken", "雞肉", "450 g"], ["Garlic", "蒜頭", "3 tbsp"], ["Shallots", "紅蔥頭", "3 tbsp"], ["Red Chilli", "紅辣椒", "3"], ["Fish Sauce", "魚露", "2 tbsp"], ["Soy Sauce", "醬油", "2 tsp"], ["Basil Leaves", "九層塔", "handful"]] },
  { id: "banh-mi-bowl", mealId: "52997", name: "Beef banh mi bowl", zh: "越式牛肉飯", cat: "Rice bowl",
    ing: [["Rice", "白米", "1 cup"], ["Ground Beef", "牛絞肉", "1 lb"], ["Cucumber", "小黃瓜", "1"], ["Carrots", "紅蘿蔔", "3 oz"], ["Garlic Clove", "蒜頭", "3"], ["Soy Sauce", "醬油", "2 oz"], ["Onion", "洋蔥", "1"], ["Lime", "萊姆", "1"]] },
  { id: "garlic-broccoli", mealId: "", name: "Garlic broccoli", zh: "蒜炒花椰菜", cat: "Side",
    ing: [["Broccoli", "花椰菜", "1 head"], ["Garlic", "蒜頭", "4 cloves"], ["Salt", "鹽", "to taste"]] },
  { id: "algerian-kefta-meatballs", mealId: "53281", name: "Algerian Kefta (Meatballs)", zh: "阿爾及利亞肉丸", cat: "Beef",
    ing: [["Ground Beef", "", "1 lb"], ["Garlic", "", "4 Cloves Crushed"], ["Onion", "", "1/2 cup"], ["Salt", "", "To taste"], ["Pepper", "", "To taste"], ["Plum Tomatoes", "", "3"]] },
  { id: "arepa-pabellon", mealId: "53334", name: "Arepa Pabellón", zh: "委內瑞拉三色玉米餅", cat: "Beef",
    ing: [["Corn Arepa Filled With Mozarella Cheese", "", "2"], ["Fried Ripe Bananas", "", "1"], ["Black Beans", "", "1 Can"], ["Pico De Gallo Sauce", "", "1"], ["Shredded Meat", "", "2kg"], ["Tomato", "", "1 chopped"]] },
  { id: "arepa-pelua", mealId: "53329", name: "Arepa pelua", zh: "委內瑞拉毛毛玉米餅", cat: "Beef",
    ing: [["Beef", "", "500g"], ["Onion", "", "1"], ["Red Pepper", "", "1"], ["Garlic", "", "2 cloves"], ["Cumin", "", "1 tsp"], ["Oregano", "", "1 tsp"]] },
  { id: "asado", mealId: "53133", name: "Asado", zh: "阿根廷烤肉", cat: "Beef",
    ing: [["Mixed Beef Cuts", "", "2kg"], ["Chorizo", "", "4"], ["Morcilla", "", "2"], ["Salt", "", "To taste"]] },
  { id: "aussie-burgers", mealId: "53099", name: "Aussie Burgers", zh: "澳式漢堡", cat: "Beef",
    ing: [["Lean Minced Steak", "", "500g"], ["Cooked Beetroot", "", "100g"], ["Naan Bread", "", "2 small"], ["Rocket", "", "50g"], ["Soured cream and chive dip", "", "4 tablespoons"]] },
  { id: "barbados-pepperpot", mealId: "53457", name: "Barbados Pepperpot", zh: "巴貝多燉肉鍋", cat: "Beef",
    ing: [["Pigs Trotters", "", "2"], ["Oxtail", "", "2 Lbs"], ["Lime juice", "", "Splash"], ["Garlic", "", "3 cloves"], ["Scotch Bonnet", "", "2"], ["Onion", "", "1 large"]] },
  { id: "beef-and-mustard-pie", mealId: "52874", name: "Beef and Mustard Pie", zh: "牛肉芥末派", cat: "Beef",
    ing: [["Beef", "", "1kg"], ["Plain Flour", "", "2 tbs"], ["Rapeseed Oil", "", "2 tbs"], ["Red Wine", "", "200ml"], ["Beef Stock", "", "400ml"], ["Onion", "", "1 finely sliced"]] },
  { id: "beef-and-oyster-pie", mealId: "52878", name: "Beef and Oyster pie", zh: "牛肉蠔派", cat: "Beef",
    ing: [["Beef", "", "900g"], ["Olive Oil", "", "3 tbs"], ["Shallots", "", "3"], ["Garlic", "", "2 cloves minced"], ["Bacon", "", "125g"], ["Thyme", "", "1 tbs chopped"]] },
  { id: "beef-asado", mealId: "53071", name: "Beef Asado", zh: "牛肉阿薩多", cat: "Beef",
    ing: [["Beef", "", "1.5kg"], ["Beef Stock Concentrate", "", "1"], ["Tomato Puree", "", "8 ounces"], ["Water", "", "3 cups"], ["Soy Sauce", "", "6 tablespoons"], ["White Wine Vinegar", "", "1 tbs"]] },
  { id: "15-minute-chicken-and-halloumi-burgers", mealId: "53085", name: "15-minute chicken & halloumi burgers", zh: "15分鐘雞肉哈羅米漢堡", cat: "Chicken",
    ing: [["Chicken Breasts", "", "2"], ["Oil", "", "1 tbsp"], ["Hotsauce", "", "4 tbsp"], ["Lemon Juice", "", "½"], ["Buns", "", "2"], ["Cheese", "", "250g"]] },
  { id: "ayam-percik", mealId: "53050", name: "Ayam Percik", zh: "馬來烤雞", cat: "Chicken",
    ing: [["Chicken Thighs", "", "6"], ["Challots", "", "16"], ["Ginger", "", "1 1/2"], ["Garlic Clove", "", "6"], ["Cayenne Pepper", "", "8"], ["Turmeric", "", "2 tbs"]] },
  { id: "belgian-waterzooi-chicken", mealId: "53466", name: "Belgian Waterzooi Chicken", zh: "比利時燉雞", cat: "Chicken",
    ing: [["Chicken Legs", "", "1"], ["Chicken Breast", "", "1"], ["Water", "", "3 Cups"], ["Carrots", "", "1 small"], ["Leek", "", "2"], ["Celery", "", "1"]] },
  { id: "bengali-chicken-curry-with-potatoes", mealId: "53453", name: "Bengali Chicken Curry with Potatoes", zh: "孟加拉馬鈴薯雞肉咖哩", cat: "Chicken",
    ing: [["Olive Oil", "", "2 tablespoons"], ["Onion", "", "2 diced"], ["Ginger Garlic Paste", "", "1 tablespoon"], ["Tomato", "", "2 diced"], ["Cayenne Pepper", "", "1 tsp"], ["Curry Powder", "", "1 tsp"]] },
  { id: "brown-stew-chicken", mealId: "52940", name: "Brown Stew Chicken", zh: "棕燉雞", cat: "Chicken",
    ing: [["Chicken", "", "1 whole"], ["Tomato", "", "1 chopped"], ["Onions", "", "2 chopped"], ["Garlic Clove", "", "2 chopped"], ["Red Pepper", "", "1 chopped"], ["Carrots", "", "1 chopped"]] },
  { id: "chick-fil-a-sandwich", mealId: "53016", name: "Chick-Fil-A Sandwich", zh: "炸雞三明治", cat: "Chicken",
    ing: [["Chicken Breast", "", "1"], ["Pickle Juice", "", "1/4 cup"], ["Egg", "", "1"], ["Milk", "", "1/4 cup"], ["Flour", "", "1/2 cup"], ["Icing Sugar", "", "1 tbs"]] },
  { id: "chicken-and-chorizo-rice-pot", mealId: "53161", name: "Chicken & chorizo rice pot", zh: "雞肉臘腸燉飯鍋", cat: "Chicken",
    ing: [["Oil", "", "1 tblsp"], ["Chicken", "", "1 whole"], ["Onion", "", "1 Large Chopped"], ["Red Pepper", "", "1 chopped"], ["Garlic", "", "3 Cloves Crushed"], ["Chorizo", "", "225g"]] },
  { id: "chicken-and-mushroom-hotpot", mealId: "52846", name: "Chicken & mushroom Hotpot", zh: "雞肉蘑菇火鍋", cat: "Chicken",
    ing: [["Butter", "", "50g"], ["Onion", "", "1 chopped"], ["Mushrooms", "", "100g"], ["Plain Flour", "", "40g"], ["Chicken Stock Cube", "", "1"], ["Nutmeg", "", "pinch"]] },
  { id: "chicken-alfredo-primavera", mealId: "52796", name: "Chicken Alfredo Primavera", zh: "雞肉阿福雷多蔬菜義大利麵", cat: "Chicken",
    ing: [["Butter", "", "2 tablespoons"], ["Olive Oil", "", "3 tablespoons"], ["Chicken", "", "5 boneless"], ["Salt", "", "1 teaspoon"], ["Squash", "", "1 cut into 1/2-inch cubes"], ["Broccoli", "", "1 Head chopped"]] },
  { id: "chicken-and-potato-roti", mealId: "53459", name: "Chicken and Potato Roti", zh: "雞肉馬鈴薯烤餅", cat: "Chicken",
    ing: [["Flour", "", "1 lb"], ["Shortening", "", "3 tablespoons"], ["Salt", "", "Pinch"], ["Water", "", "Splash"], ["Chicken Breast", "", "6"], ["Parsley", "", "Pinch"]] },
  { id: "bleskiver", mealId: "53120", name: "Æbleskiver", zh: "丹麥小圓球鬆餅", cat: "Dessert",
    ing: [["Flour", "", "2 cups"], ["Salt", "", "1 teaspoon"], ["Granulated Sugar", "", "2 tblsp"], ["Baking Powder", "", "1 teaspoon"], ["Cardamom", "", "1/2 teaspoon"], ["Egg", "", "3"]] },
  { id: "alfajores", mealId: "53138", name: "Alfajores", zh: "阿根廷夾心餅", cat: "Dessert",
    ing: [["All purpose flour", "", "300g"], ["Cornstarch", "", "200g"], ["Butter", "", "200g"], ["Sugar", "", "100g"], ["Egg Yolks", "", "2"], ["Lemon Zest", "", "1 teaspoon"]] },
  { id: "anzac-biscuits", mealId: "53111", name: "Anzac biscuits", zh: "澳紐軍團餅乾", cat: "Dessert",
    ing: [["Porridge oats", "", "85g"], ["Desiccated Coconut", "", "85g"], ["Plain Flour", "", "100g"], ["Caster Sugar", "", "100g"], ["Butter", "", "100g"], ["Golden Syrup", "", "1 tblsp"]] },
  { id: "apam-balik", mealId: "53049", name: "Apam balik", zh: "曼煎糕", cat: "Dessert",
    ing: [["Milk", "", "200ml"], ["Oil", "", "60ml"], ["Eggs", "", "2"], ["Flour", "", "1600g"], ["Baking Powder", "", "3 tsp"], ["Salt", "", "1/2 tsp"]] },
  { id: "apple-and-blackberry-crumble", mealId: "52893", name: "Apple & Blackberry Crumble", zh: "蘋果黑莓奶酥", cat: "Dessert",
    ing: [["Plain Flour", "", "120g"], ["Caster Sugar", "", "60g"], ["Butter", "", "60g"], ["Braeburn Apples", "", "300g"], ["Butter", "", "30g"], ["Demerara Sugar", "", "30g"]] },
  { id: "apple-cake", mealId: "53380", name: "Apple cake", zh: "蘋果蛋糕", cat: "Dessert",
    ing: [["Eggs", "", "4"], ["Sugar", "", "200g"], ["Self-raising Flour", "", "200g"], ["Melted Butter", "", "200g"], ["Vanilla Extract", "", "1 tsp"], ["Ground Cinnamon", "", "1 tsp"]] },
  { id: "apple-frangipan-tart", mealId: "52768", name: "Apple Frangipan Tart", zh: "蘋果杏仁塔", cat: "Dessert",
    ing: [["digestive biscuits", "", "175g/6oz"], ["butter", "", "75g/3oz"], ["Bramley apples", "", "200g/7oz"], ["Salted Butter", "", "75g/3oz"], ["caster sugar", "", "75g/3oz"], ["free-range eggs, beaten", "", "2"]] },
  { id: "apple-pie", mealId: "53575", name: "Apple Pie", zh: "蘋果派", cat: "Dessert",
    ing: [["Apples", "", "4"], ["Eggs", "", "2"], ["Sugar", "", "125ml"], ["Flour", "", "1 1/2 cups"], ["Salt", "", "1/2 tsp"], ["Bicarbonate Of Soda", "", "1 tsp"]] },
  { id: "apple-pie-pops", mealId: "53568", name: "Apple pie pops", zh: "蘋果派棒棒糖", cat: "Dessert",
    ing: [["Sugar", "", "1 tablespoon"], ["All purpose flour", "", "1 1/2 cups"], ["Salt", "", "1 tsp"], ["Unsalted Butter", "", "4 oz"], ["Shortening", "", "1 tablespoon"], ["Cold Water", "", "1/4 cup"]] },
  { id: "apricot-and-turkish-delight-mess", mealId: "53276", name: "Apricot & Turkish delight mess", zh: "杏桃土耳其軟糖甜點", cat: "Dessert",
    ing: [["Mascarpone", "", "100g"], ["Greek Yogurt", "", "50g"], ["Icing Sugar", "", "25g"], ["Orange Blossom Water", "", "2 tablespoons"], ["Meringue Nests", "", "1"], ["Apricot", "", "3"]] },
  { id: "adana-kebab", mealId: "53262", name: "Adana kebab", zh: "阿達納烤肉串", cat: "Lamb",
    ing: [["Romano Pepper", "", "2 large"], ["Lamb Mince", "", "800g"], ["Red Pepper Paste", "", "3 tablespoons"], ["Pul Biber", "", "1 tablespoon"], ["Sunflower Oil", "", "3 tablespoons"]] },
  { id: "chilli-ginger-lamb-chops", mealId: "53265", name: "Chilli ginger lamb chops", zh: "辣椒薑味羊排", cat: "Lamb",
    ing: [["Garlic", "", "4 Cloves Crushed"], ["Ginger", "", "1 tblsp"], ["Lemon Juice", "", "1 tblsp"], ["Olive Oil", "", "1 tblsp"], ["Chili Powder", "", "1/2 tsp"], ["Cumin", "", "1 tsp"]] },
  { id: "chorba-hamra-bel-frik-algerian-lamb-tomato-and-freekeh-soup", mealId: "53289", name: "Chorba Hamra bel Frik (Algerian Lamb, Tomato, and Freekeh Soup)", zh: "阿爾及利亞羊肉番茄青麥湯", cat: "Lamb",
    ing: [["Freekeh", "", "1 cup"], ["Lamb", "", "12 ounces"], ["Onion", "", "1 finely chopped"], ["Black Pepper", "", "1 tsp"], ["Paprika", "", "1 tsp"], ["Ground Cinnamon", "", "1 tsp"]] },
  { id: "farikal-norwegian-national-dish", mealId: "53123", name: "Fårikål (Norwegian National Dish)", zh: "挪威燉羊肉高麗菜", cat: "Lamb",
    ing: [["Lamb", "", "3 Lbs"], ["White Cabbage", "", "1 head"], ["Whole black peppercorns", "", "3 tablespoons"], ["Salt", "", "3 tsp"], ["Water", "", "1 1/2 cups"], ["Flour", "", "5 tablespoons"]] },
  { id: "hot-cumin-lamb-wrap-with-crunchy-slaw-and-spicy-mayo", mealId: "53258", name: "Hot cumin lamb wrap with crunchy slaw & spicy mayo", zh: "孜然羊肉捲餅佐辣美乃滋", cat: "Lamb",
    ing: [["Lamb Leg", "", "4 small"], ["Olive Oil", "", "2 tsp"], ["Ground Cumin", "", "1 tsp"], ["Sugar", "", "1 tablespoon"], ["White Wine Vinegar", "", "3 tablespoons"], ["Carrots", "", "2"]] },
  { id: "imam-bayildi-with-bbq-lamb-and-tzatziki", mealId: "53253", name: "Imam bayildi with BBQ lamb & tzatziki", zh: "茄子鑲羊肉佐希臘優格醬", cat: "Lamb",
    ing: [["Aubergine", "", "3"], ["Olive Oil", "", "2 tablespoons"], ["Onion", "", "1 chopped"], ["Garlic", "", "2 cloves chopped"], ["Cinnamon", "", "1 tsp"], ["Tomato", "", "8"]] },
  { id: "kapsalon", mealId: "52769", name: "Kapsalon", zh: "卡普沙隆蓋飯", cat: "Lamb",
    ing: [["Fries", "", "250 Grams"], ["Doner Meat", "", "500 Grams"], ["Garlic sauce", "", "Topping"], ["Hotsauce", "", "Topping"], ["Lettuce", "", "1 Bulb"], ["Tomato", "", "1"]] },
  { id: "kelem-dolmasi", mealId: "53449", name: "Kelem dolmasi", zh: "高麗菜捲", cat: "Lamb",
    ing: [["Lamb Mince", "", "500g"], ["Cabbage", "", "1 large"], ["Onion", "", "8 oz"], ["Salt", "", "Pinch"], ["Pepper", "", "Pinch"], ["Turmeric", "", "1/2 tsp"]] },
  { id: "keleya-zaara", mealId: "52974", name: "Keleya Zaara", zh: "凱蕾亞查拉燉肉", cat: "Lamb",
    ing: [["Olive Oil", "", "4 tbs"], ["Lamb", "", "750g"], ["Saffron", "", "1 1/2 tsp"], ["Onion", "", "1 Large Chopped"], ["Water", "", "25 ml"], ["Parsley", "", "30g"]] },
  { id: "kofta-burgers", mealId: "53257", name: "kofta burgers", zh: "科夫塔漢堡", cat: "Lamb",
    ing: [["Lamb", "", "1kg"], ["Onion", "", "2"], ["Garlic Bulb", "", "1"], ["Garam Masala", "", "6 tablespoons"], ["Coriander", "", "Bunch"], ["Chilli Sauce", "", "1 tablespoon"]] },
  { id: "achiote-oil-aceite-achiotado-recipe", mealId: "53527", name: "Achiote Oil (Aceite Achiotado) Recipe", zh: "胭脂樹籽油", cat: "Miscellaneous",
    ing: [["Vegetable Oil", "", "2 cups"], ["Achiote Seeds", "", "4 tablespoons"]] },
  { id: "aji-de-aguacate-recipe-colombian-spicy-avocado-sauce", mealId: "53525", name: "Ají de Aguacate Recipe (Colombian Spicy Avocado Sauce)", zh: "哥倫比亞酪梨辣醬", cat: "Miscellaneous",
    ing: [["Avocado", "", "2"], ["Habanero Pepper", "", "1"], ["Egg", "", "1"], ["Lime", "", "Juice of 2"], ["Salt", "", "To taste"], ["Vinegar", "", "2 tablespoons"]] },
  { id: "bean-and-sausage-hotpot", mealId: "52848", name: "Bean & Sausage Hotpot", zh: "豆子香腸鍋", cat: "Miscellaneous",
    ing: [["Sausages", "", "8 large"], ["Tomato Sauce", "", "1 Jar"], ["Butter Beans", "", "1200g"], ["Black Treacle", "", "1 tbls"], ["English Mustard", "", "1 tsp"]] },
  { id: "bolita-di-keshi", mealId: "53438", name: "Bolita di Keshi", zh: "起司肉丸", cat: "Miscellaneous",
    ing: [["Cheddar Cheese", "", "1 lb"], ["Feta", "", "1 lb"], ["Eggs", "", "1 beaten"], ["Cornstarch", "", "5 tablespoons"]] },
  { id: "callaloo-jamaican-style", mealId: "52939", name: "Callaloo Jamaican Style", zh: "牙買加卡拉魯燉菜", cat: "Miscellaneous",
    ing: [["Kale", "", "1 bunch"], ["Bacon", "", "2 strips"], ["Garlic", "", "3 cloves Chopped"], ["Onion", "", "1 medium"], ["Paprika", "", "1/2 tsp"], ["Thyme", "", "1 Sprig"]] },
  { id: "chakchouka", mealId: "52969", name: "Chakchouka", zh: "北非蛋", cat: "Miscellaneous",
    ing: [["Tomatoes", "", "4"], ["Olive Oil", "", "2 tbs"], ["Onion", "", "1 Diced"], ["Red Pepper", "", "1 sliced"], ["Green Pepper", "", "1 sliced"], ["Garlic", "", "3 Cloves Crushed"]] },
  { id: "clear-soup-with-semolina-dumplings", mealId: "53446", name: "Clear Soup with Semolina Dumplings", zh: "粗粒小麥丸子清湯", cat: "Miscellaneous",
    ing: [["Semolina", "", "120g"], ["Butter", "", "60g"], ["Egg", "", "1"], ["Salt", "", "Pinch"], ["Nutmeg", "", "Pinch"], ["Oil", "", "Splash"]] },
  { id: "duck-confit", mealId: "52907", name: "Duck Confit", zh: "油封鴨", cat: "Miscellaneous",
    ing: [["Sea Salt", "", "Handful"], ["Bay Leaf", "", "4"], ["Garlic", "", "4 cloves"], ["Thyme", "", "Handful"], ["Duck Legs", "", "4"], ["White Wine", "", "100ml"]] },
  { id: "french-lentils-with-garlic-and-thyme", mealId: "52815", name: "French Lentils With Garlic and Thyme", zh: "法式蒜香百里香扁豆", cat: "Miscellaneous",
    ing: [["Olive Oil", "", "3 tablespoons"], ["Onion", "", "1"], ["Garlic", "", "2 cloves"], ["Carrots", "", "1"], ["French Lentils", "", "2 1/4 cups"], ["Thyme", "", "1 teaspoon"]] },
  { id: "french-omelette", mealId: "52915", name: "French Omelette", zh: "法式歐姆蛋", cat: "Miscellaneous",
    ing: [["Eggs", "", "3"], ["Butter", "", "2 knobs"], ["Parmesan", "", "1 tsp"], ["Tarragon Leaves", "", "3 chopped"], ["Parsley", "", "1 tbs chopped"], ["Chives", "", "1 tbs chopped"]] },
  { id: "chilli-prawn-linguine", mealId: "52839", name: "Chilli prawn linguine", zh: "辣椒蝦仁扁麵", cat: "Pasta",
    ing: [["Linguine Pasta", "", "280g"], ["Sugar Snap Peas", "", "200g"], ["Olive Oil", "", "2 tblsp"], ["Garlic Clove", "", "2 cloves chopped"], ["Red Chilli", "", "1 large"], ["King Prawns", "", "24 Skinned"]] },
  { id: "fettuccine-alfredo", mealId: "53064", name: "Fettuccine Alfredo", zh: "奶油培根寬麵", cat: "Pasta",
    ing: [["Fettuccine", "", "1 lb"], ["Heavy Cream", "", "1/2 cup"], ["Butter", "", "1/2 cup"], ["Parmesan", "", "1/2 cup"], ["Parsley", "", "2 tbsp"], ["Black Pepper", "", ""]] },
  { id: "fettucine-alfredo", mealId: "52835", name: "Fettucine alfredo", zh: "奶油寬麵", cat: "Pasta",
    ing: [["Clotted Cream", "", "227g"], ["Butter", "", "25g"], ["Corn Flour", "", "1 tsp"], ["Parmesan Cheese", "", "100g"], ["Nutmeg", "", "Grated"], ["Fettuccine", "", "250g"]] },
  { id: "grilled-mac-and-cheese-sandwich", mealId: "52829", name: "Grilled Mac and Cheese Sandwich", zh: "烤起司通心麵三明治", cat: "Pasta",
    ing: [["Macaroni", "", "8 ounces (230 grams)"], ["Plain Flour", "", "1/3 cup"], ["Mustard Powder", "", "3/4 teaspoon"], ["Garlic powder", "", "1/2 teaspoon"], ["Kosher salt", "", "1/2 teaspoon"], ["Black pepper", "", "1/2 teaspoon"]] },
  { id: "lasagna-sandwiches", mealId: "52987", name: "Lasagna Sandwiches", zh: "千層麵三明治", cat: "Pasta",
    ing: [["Sour Cream", "", "1/4 cup"], ["Chopped Onion", "", "2 tbs"], ["Dried Oregano", "", "1/2 tbs"], ["Salt", "", "1/4 tsp"], ["Bread", "", "8 slices"], ["Bacon", "", "8 slices"]] },
  { id: "lasagne", mealId: "52844", name: "Lasagne", zh: "義式千層麵", cat: "Pasta",
    ing: [["Olive Oil", "", "1 tblsp"], ["Bacon", "", "2"], ["Onion", "", "1 finely chopped"], ["Celery", "", "1 Stick"], ["Carrots", "", "1 medium"], ["Garlic", "", "2 cloves chopped"]] },
  { id: "macaroni-pie", mealId: "53461", name: "Macaroni Pie", zh: "通心麵派", cat: "Pasta",
    ing: [["Macaroni", "", "250g"], ["Butter", "", "1 tablespoon"], ["Cheddar Cheese", "", "375g"], ["Egg", "", "1"], ["Milk", "", "250ml"], ["Ground Onion", "", "2 tsp"]] },
  { id: "macaroni-pudding", mealId: "53504", name: "Macaroni Pudding", zh: "通心麵布丁", cat: "Pasta",
    ing: [["Macaroni", "", "4 cups"], ["Evaporated Milk", "", "4 cups"], ["Water", "", "1 cup"], ["Sugar", "", "3 Cups"], ["Salt", "", "2 tsp"], ["Eggs", "", "4"]] },
  { id: "pilchard-puttanesca", mealId: "52837", name: "Pilchard puttanesca", zh: "沙丁魚義式辣醬麵", cat: "Pasta",
    ing: [["Spaghetti", "", "300g"], ["Olive Oil", "", "1 tbls"], ["Onion", "", "1 finely chopped"], ["Garlic", "", "2 cloves minced"], ["Red Chilli", "", "1"], ["Tomato Puree", "", "1 tbls"]] },
  { id: "spaghetti-alla-carbonara", mealId: "52982", name: "Spaghetti alla Carbonara", zh: "培根蛋奶義大利麵", cat: "Pasta",
    ing: [["Spaghetti", "", "320g"], ["Egg Yolks", "", "6"], ["Salt", "", "As required"], ["Bacon", "", "150g"], ["Pecorino", "", "50g"], ["Black Pepper", "", "As required"]] },
  { id: "bubble-and-squeak", mealId: "52885", name: "Bubble & Squeak", zh: "高麗菜馬鈴薯煎餅", cat: "Pork",
    ing: [["Butter", "", "1 tbs"], ["Bacon", "", "4"], ["Onion", "", "1 finely sliced"], ["Garlic Clove", "", "1 chopped"], ["Brussels Sprouts", "", "20"], ["Potatoes", "", "400g"]] },
  { id: "arroz-al-horno-baked-rice", mealId: "53156", name: "Arroz al horno (baked rice)", zh: "西班牙烤飯", cat: "Pork",
    ing: [["Extra Virgin Olive Oil", "", "2 tbsp"], ["Pork belly slices", "", "800g"], ["Black Pudding", "", "150g"], ["Bacon lardon", "", "100g"], ["Onion", "", "1 chopped"], ["Red Pepper", "", "2"]] },
  { id: "bai-sach-chrouk-grilled-pork-with-rice", mealId: "53496", name: "Bai Sach Chrouk – Grilled Pork with Rice", zh: "柬埔寨烤豬肉飯", cat: "Pork",
    ing: [["Pork Shoulder", "", "650g"], ["Coconut Milk", "", "1/4 cup"], ["Soy Sauce", "", "3 tablespoons"], ["Oyster Sauce", "", "2 tablespoons"], ["Honey", "", "2 tablespoons"], ["Garlic", "", "4 cloves"]] },
  { id: "barbecue-pork-buns", mealId: "53242", name: "Barbecue pork buns", zh: "叉燒包", cat: "Pork",
    ing: [["Sugar", "", "85g"], ["White Bread Mix", "", "500g"], ["Sunflower Oil", "", "1 tablespoon"], ["Bacon", "", "12"], ["Ginger", "", "Knob"], ["Garlic", "", "2 cloves chopped"]] },
  { id: "bbq-pork-sloppy-joes", mealId: "52995", name: "BBQ Pork Sloppy Joes", zh: "烤肉豬肉邋遢喬三明治", cat: "Pork",
    ing: [["Potatoes", "", "2"], ["Red Onions", "", "1"], ["Garlic", "", "2 cloves"], ["Lime", "", "1"], ["Bread", "", "2"], ["Pork", "", "1 lb"]] },
  { id: "belgian-stoemp", mealId: "53468", name: "Belgian Stoemp", zh: "比利時馬鈴薯泥", cat: "Pork",
    ing: [["Sausages", "", "2"], ["Potatoes", "", "450g"], ["Savoy Cabbage", "", "200g"], ["Garlic", "", "3 cloves"], ["Parsley", "", "1 Handfull"], ["Onion", "", "1 small finely diced"]] },
  { id: "bigos-hunters-stew", mealId: "53018", name: "Bigos (Hunters Stew)", zh: "波蘭獵人燉菜", cat: "Pork",
    ing: [["Bacon", "", "2 sliced"], ["Kielbasa", "", "1 lb"], ["Pork", "", "1 lb"], ["Flour", "", "1/4 cup"], ["Garlic", "", "3 chopped"], ["Onion", "", "1 Diced"]] },
  { id: "boxty-breakfast", mealId: "53036", name: "Boxty Breakfast", zh: "愛爾蘭馬鈴薯煎餅早餐", cat: "Pork",
    ing: [["Potatoes", "", "4 large"], ["Spring Onions", "", "1 bunch"], ["Plain Flour", "", "100g"], ["Egg White", "", "1"], ["Milk", "", "150ml"], ["Bicarbonate Of Soda", "", "1 tsp"]] },
  { id: "bryndzove-halusky", mealId: "53190", name: "Bryndzové Halušky", zh: "斯洛伐克起司馬鈴薯麵疙瘩", cat: "Pork",
    ing: [["Potatoes", "", "500g"], ["Plain Flour", "", "200g"], ["Egg", "", "1"], ["Salt", "", "1 teaspoon"], ["Bryndza cheese", "", "250g"], ["Bacon", "", "200g"]] },
  { id: "cambodian-stir-fried-morning-glory-with-pork-fermented-soybeans-and-garlic", mealId: "53418", name: "Cambodian Stir-fried Morning Glory with Pork, Fermented Soybeans, and Garlic", zh: "柬埔寨蒜香發酵豆炒空心菜配豬肉", cat: "Pork",
    ing: [["Morning Glory", "", "1 bunch"], ["Minced Pork", "", "150g"], ["Soya Bean", "", "2 tablespoons"], ["Garlic", "", "4 Cloves Chopped"], ["Oil", "", "For frying"], ["Fish Sauce", "", "Dash"]] },
  { id: "acaraje-black-eyed-pea-fritters-with-shrimp-filling", mealId: "53483", name: "Acaraje black-eyed pea fritters with shrimp filling", zh: "黑眼豆蝦仁炸餅", cat: "Seafood",
    ing: [["Black Eyed Peas", "", "800g"], ["Garlic", "", "1 clove"], ["Green Chilli", "", "1"], ["Red Onions", "", "1 small finely diced"], ["Plain Flour", "", "2 tablespoons"], ["Salt", "", "1 tsp"]] },
  { id: "amok-trey-cambodian-fish-curry", mealId: "53495", name: "Amok Trey – Cambodian Fish Curry", zh: "柬埔寨魚咖哩", cat: "Seafood",
    ing: [["Fish fillet", "", "1 lb"], ["Coconut Milk", "", "1 Can"], ["Red Curry Paste", "", "2 tablespoons"], ["Fish Sauce", "", "1 tablespoon"], ["Brown Sugar", "", "1 tsp"], ["Chicken Stock", "", "1 cup"]] },
  { id: "arroz-con-gambas-y-calamar", mealId: "53147", name: "Arroz con gambas y calamar", zh: "蝦仁花枝燉飯", cat: "Seafood",
    ing: [["Raw King Prawns", "", "24"], ["Olive Oil", "", "2 tbsp"], ["Onion", "", "1 small"], ["Bay Leaf", "", "1"], ["Saffron", "", "1 pinch"], ["Paella Rice", "", "450g"]] },
  { id: "bahia-style-moqueca-prawn-stew", mealId: "53481", name: "Bahia-style Moqueca prawn stew", zh: "巴伊亞風蝦仁燉菜", cat: "Seafood",
    ing: [["Raw King Prawns", "", "450g"], ["Lime juice", "", "75 ml"], ["Garlic", "", "3 cloves Chopped"], ["Coconut Oil", "", "3 tablespoons"], ["Spring Onions", "", "4 Chopped"], ["Onion", "", "1"]] },
  { id: "baked-salmon-with-fennel-and-tomatoes", mealId: "52959", name: "Baked salmon with fennel & tomatoes", zh: "烤鮭魚佐茴香番茄", cat: "Seafood",
    ing: [["Fennel", "", "2 medium"], ["Parsley", "", "2 tbs chopped"], ["Lemon", "", "Juice of 1"], ["Cherry Tomatoes", "", "175g"], ["Olive Oil", "", "1 tbs"], ["Salmon", "", "350g"]] },
  { id: "balchi-di-pisca", mealId: "53440", name: "Balchi di Pisca", zh: "荷屬安地列斯炸魚餅", cat: "Seafood",
    ing: [["Salt Cod", "", "1"], ["Potatoes", "", "3 Medium"], ["Tomato", "", "1"], ["Green Pepper", "", "1/2"], ["Onion", "", "1 medium"], ["Garlic", "", "1 clove peeled sliced"]] },
  { id: "bang-bang-prawn-salad", mealId: "53239", name: "Bang bang prawn salad", zh: "棒棒蝦沙拉", cat: "Seafood",
    ing: [["Rice Noodles", "", "140g"], ["Peanut Butter", "", "3 tablespoons"], ["Coconut Milk", "", "4 tablespoons"], ["sweet chilli sauce", "", "3 tablespoons"], ["Spring Onions", "", "3 sliced thinly"], ["Cucumber", "", "1 sliced"]] },
  { id: "bangladeshi-fish-curry-with-daikon", mealId: "53451", name: "Bangladeshi fish curry with daikon", zh: "孟加拉白蘿蔔魚咖哩", cat: "Seafood",
    ing: [["White Fish", "", "450g"], ["Daikon Radish", "", "450g"], ["Vegetable Oil", "", "4 tablespoons"], ["Garlic", "", "4 cloves"], ["Onion", "", "1 medium"], ["Salt", "", "2 tsp"]] },
  { id: "barramundi-with-moroccan-spices", mealId: "53103", name: "Barramundi with Moroccan spices", zh: "摩洛哥香料肺魚", cat: "Seafood",
    ing: [["barramundi", "", "2 x 400g"], ["Ground Cumin", "", "1/2 teaspoon"], ["Coriander", "", "1/2 tsp"], ["Paprika", "", "Pinch"], ["Chili Powder", "", "Pinch"], ["Garlic Clove", "", "2"]] },
  { id: "cajun-spiced-fish-tacos", mealId: "52819", name: "Cajun spiced fish tacos", zh: "卡疆香料魚塔可", cat: "Seafood",
    ing: [["cajun", "", "2 tbsp"], ["cayenne pepper", "", "1 tsp"], ["white fish", "", "4 fillets"], ["vegetable oil", "", "1 tsp"], ["flour tortilla", "", "8"], ["avocado", "", "1 sliced"]] },
  { id: "air-fryer-egg-rolls", mealId: "53373", name: "Air Fryer Egg Rolls", zh: "氣炸鍋蛋捲", cat: "Side",
    ing: [["Olive Oil", "", "1 tablespoon"], ["Ground Pork", "", "1 lb"], ["Garlic", "", "1 clove peeled crushed"], ["Ginger", "", "1 tablespoon"], ["Carrots", "", "1 medium"], ["Scallions", "", "3 chopped"]] },
  { id: "algerian-bouzgene-berber-bread-with-roasted-pepper-sauce", mealId: "53284", name: "Algerian Bouzgene Berber Bread with Roasted Pepper Sauce", zh: "阿爾及利亞柏柏爾麵包佐烤椒醬", cat: "Side",
    ing: [["Red Pepper", "", "2"], ["Tomato", "", "4"], ["Olive Oil", "", "1 tablespoon"], ["Garlic", "", "4 Cloves Chopped"], ["Jalapeno", "", "1 chopped"], ["Salt", "", "To taste"]] },
  { id: "algerian-carrots", mealId: "53282", name: "Algerian Carrots", zh: "阿爾及利亞胡蘿蔔沙拉", cat: "Side",
    ing: [["Water", "", "1 1/2 cup"], ["Carrots", "", "2 Lbs"], ["Olive Oil", "", "5 tablespoons"], ["Salt", "", "1 tsp"], ["Black Pepper", "", "1/2 teaspoon"], ["Ground Cinnamon", "", "1/2 teaspoon"]] },
  { id: "almojabanas-colombian-cheese-bread", mealId: "53529", name: "Almojábanas (Colombian Cheese Bread)", zh: "哥倫比亞起司麵包", cat: "Side",
    ing: [["Cornmeal", "", "1 1/4 cup"], ["Queso Fresco", "", "3 Cups"], ["Mozzarella", "", "1 cup"], ["Butter", "", "2 tablespoons"], ["Baking Powder", "", "1 tsp"], ["Salt", "", "1/4 tsp"]] },
  { id: "apple-potato-mash-hete-bliksem", mealId: "53389", name: "Apple Potato Mash (Hete bliksem)", zh: "蘋果馬鈴薯泥", cat: "Side",
    ing: [["Apples", "", "250g"], ["Potatoes", "", "250g"], ["Cinnamon Stick", "", "1"], ["Maple Syrup", "", "1 tsp"], ["Ground Cinnamon", "", "Sprinkling"], ["Bacon", "", "4"]] },
  { id: "arepa", mealId: "53439", name: "Arepa", zh: "委內瑞拉玉米餅", cat: "Side",
    ing: [["Salt", "", "1 tsp"], ["Corn Flour", "", "1 cup"], ["Warm Water", "", "1 1/4 cup"]] },
  { id: "baba-ghanoush", mealId: "53094", name: "Baba Ghanoush", zh: "茄子芝麻醬", cat: "Side",
    ing: [["Egg Plants", "", "4 large"], ["Garlic", "", "2 cloves"], ["Kosher Salt", "", "2 teaspoons"], ["Lemon", "", "1"], ["Tahini", "", "3 tablespoons"], ["Extra Virgin Olive Oil", "", "3 tablespoons"]] },
  { id: "bajan-salt-bread-recipe", mealId: "53456", name: "Bajan Salt Bread Recipe", zh: "巴貝多鹽麵包", cat: "Side",
    ing: [["Yeast", "", "2 tubs"], ["Sugar", "", "2 tsp"], ["Salt", "", "1 tsp"], ["Vegetable Oil", "", "2 tablespoons"], ["Flour", "", "6 cups"], ["Warm Water", "", "2 1/2 cups"]] },
  { id: "bajan-sweet-bread", mealId: "53460", name: "Bajan Sweet Bread", zh: "巴貝多甜麵包", cat: "Side",
    ing: [["Coconut", "", "2 1/2 cups"], ["Melted Butter", "", "1/2 cup"], ["Flour", "", "4 cups"], ["Shortening", "", "1 tablespoon"], ["Baking Powder", "", "1 tablespoon"], ["Salt", "", "1 tsp"]] },
  { id: "baked-yuca-fries", mealId: "53548", name: "Baked Yuca Fries", zh: "烤木薯條", cat: "Side",
    ing: [["Yuca", "", "2 large"], ["Extra Virgin Olive Oil", "", "2 tablespoons"], ["Chilli Powder", "", "1 tsp"], ["Kosher Salt", "", "Pinch"], ["Ground Black Pepper", "", "Pinch"], ["Avocado", "", "1 large"]] },
  { id: "ajo-blanco", mealId: "53169", name: "Ajo blanco", zh: "西班牙白蒜湯", cat: "Starter",
    ing: [["White bread", "", "150g"], ["Almonds", "", "200g"], ["Extra Virgin Olive Oil", "", "50 ml"], ["Garlic Clove", "", "1"], ["Red Wine Vinegar", "", "1 ½ tbsp"]] },
  { id: "baked-brie-with-sorrel-jam", mealId: "53559", name: "Baked brie with sorrel jam", zh: "烤布里起司佐酸模果醬", cat: "Starter",
    ing: [["Dried Sorrel", "", "1 cup"], ["Brown Sugar", "", "2 cups"], ["Ground Ginger", "", "1 tsp"], ["Cinnamon", "", "1/4 cup"], ["vanilla pod", "", "1"], ["Orange", "", "Zest of 1"]] },
  { id: "black-bean-soup", mealId: "53546", name: "Black Bean soup", zh: "黑豆湯", cat: "Starter",
    ing: [["Extra Virgin Olive Oil", "", "2 tablespoons"], ["Red Onions", "", "1 medium"], ["Jalapeno", "", "1"], ["Garlic", "", "2 cloves minced"], ["Tomato Puree", "", "1 tablespoon"], ["Kosher Salt", "", "Pinch"]] },
  { id: "broccoli-and-stilton-soup", mealId: "52842", name: "Broccoli & Stilton soup", zh: "花椰菜史帝爾頓起司湯", cat: "Starter",
    ing: [["Rapeseed Oil", "", "2 tblsp"], ["Onion", "", "1 finely chopped"], ["Celery", "", "1"], ["Leek", "", "1 sliced"], ["Potatoes", "", "1 medium"], ["Butter", "", "1 knob"]] },
  { id: "clam-chowder", mealId: "52840", name: "Clam chowder", zh: "蛤蜊巧達湯", cat: "Starter",
    ing: [["Clams", "", "1½ kg"], ["Butter", "", "50g"], ["Bacon", "", "150g"], ["Onion", "", "1 finely chopped"], ["Thyme", "", "sprigs of fresh"], ["Bay Leaf", "", "1"]] },
  { id: "colombian-style-stuffed-potatoes", mealId: "53526", name: "Colombian Style Stuffed Potatoes", zh: "哥倫比亞鑲馬鈴薯", cat: "Starter",
    ing: [["Vegetable Oil", "", "For frying"], ["Potatoes", "", "5"], ["Salt", "", "1/4 tsp"], ["Olive Oil", "", "1 tablespoon"], ["Tomato", "", "1 cup"], ["Onion", "", "1/3 cup"]] },
  { id: "cream-cheese-tart", mealId: "52779", name: "Cream Cheese Tart", zh: "奶油起司塔", cat: "Starter",
    ing: [["Flour", "", "250g"], ["Butter", "", "125g"], ["Egg", "", "1"], ["Salt", "", "Pinch"], ["Cheese", "", "300g"], ["Milk", "", "100ml milk"]] },
  { id: "creamy-tomato-soup", mealId: "52841", name: "Creamy Tomato Soup", zh: "奶油番茄湯", cat: "Starter",
    ing: [["Olive Oil", "", "3 tbsp"], ["Onions", "", "2 chopped"], ["Celery", "", "2 sticks"], ["Carrots", "", "300g"], ["Potatoes", "", "500g"], ["Bay Leaf", "", "4"]] },
  { id: "dominican-bakes", mealId: "53567", name: "Dominican Bakes", zh: "多明尼加炸麵包", cat: "Starter",
    ing: [["All purpose flour", "", "4 cups"], ["Baking Powder", "", "1 tablespoon"], ["Salt", "", "1 tablespoon"], ["Sugar", "", "1/2 tbs"], ["Milk", "", "2 cups"], ["Butter", "", "1 ½ tbsp"]] },
  { id: "mantu-afghan-dumpling", mealId: "53402", name: "Mantu Afghan Dumpling", zh: "阿富汗餃子", cat: "Starter",
    ing: [["Plain Flour", "", "450g"], ["Water", "", "225ml"], ["Lamb", "", "450g"], ["Green Chilli", "", "1"], ["Onions", "", "450g"], ["Black Pepper", "", "2 tblsp"]] },
  { id: "fasoliyyeh-bi-z-zayt-syrian-green-beans-with-olive-oil", mealId: "53092", name: "Fasoliyyeh Bi Z-Zayt (Syrian Green Beans with Olive Oil)", zh: "敘利亞橄欖油四季豆", cat: "Vegan",
    ing: [["Green Beans", "", "16 ounces"], ["Olive Oil", "", "1/4 cup"], ["Salt", "", "Dash"], ["Garlic", "", "1 clove"], ["Cilantro", "", "1/4 cup"]] },
  { id: "padron-peppers", mealId: "53150", name: "Padron peppers", zh: "帕德龍青椒", cat: "Vegan",
    ing: [["Olive Oil", "", "1 tablespoon"], ["Padron peppers", "", "500g"]] },
  { id: "red-onion-pickle", mealId: "53115", name: "Red onion pickle", zh: "紅洋蔥泡菜", cat: "Vegan",
    ing: [["Red Onions", "", "3 Large"], ["Sea Salt", "", "2 tsp"], ["Cider Vinegar", "", "200ml"], ["Granulated Sugar", "", "50g"], ["Black Pepper", "", "1 tsp"], ["Bay Leaves", "", "4"]] },
  { id: "roast-fennel-and-aubergine-paella", mealId: "52942", name: "Roast fennel and aubergine paella", zh: "烤茴香茄子西班牙燉飯", cat: "Vegan",
    ing: [["Baby Aubergine", "", "6 small"], ["Fennel", "", "4 small"], ["Red Pepper", "", "1 thinly sliced"], ["Courgettes", "", "1 medium"], ["Onion", "", "1 finely chopped"], ["Paella Rice", "", "300g"]] },
  { id: "vegan-banh-mi", mealId: "53250", name: "Vegan banh mi", zh: "純素越式法國麵包", cat: "Vegan",
    ing: [["Raw Vegetables", "", "150g"], ["Vegan White Wine Vinegar", "", "3 tablespoons"], ["Golden Caster Sugar", "", "1 tsp"], ["Baguette", "", "1 large"], ["Hummus", "", "100g"], ["Tempeh", "", "175g"]] },
  { id: "vegan-chocolate-cake", mealId: "52794", name: "Vegan Chocolate Cake", zh: "純素巧克力蛋糕", cat: "Vegan",
    ing: [["Self-raising Flour", "", "1 1/4 cup"], ["coco sugar", "", "1/2 cup"], ["cacao", "", "1/3 cup raw"], ["baking powder", "", "1 tsp"], ["flax eggs", "", "2"], ["almond milk", "", "1/2 cup"]] },
  { id: "vegan-lasagna", mealId: "52775", name: "Vegan Lasagna", zh: "純素千層麵", cat: "Vegan",
    ing: [["green red lentils", "", "1 cups"], ["Carrots", "", "1"], ["onion", "", "1"], ["zucchini", "", "1 small"], ["coriander", "", "sprinking"], ["spinach", "", "150g"]] },
  { id: "air-fryer-patatas-bravas", mealId: "53158", name: "Air fryer patatas bravas", zh: "氣炸鍋辣馬鈴薯", cat: "Vegetarian",
    ing: [["Potatoes", "", "900g"], ["Olive Oil", "", "3 tablespoons"], ["Onion", "", "1 chopped"], ["Garlic", "", "1 clove peeled crushed"], ["Paprika", "", "1 tblsp"], ["Tomato Puree", "", "1 tblsp"]] },
  { id: "algerian-flafla-bell-pepper-salad", mealId: "53288", name: "Algerian Flafla (Bell Pepper Salad)", zh: "阿爾及利亞甜椒沙拉", cat: "Vegetarian",
    ing: [["Green Pepper", "", "3"], ["Olive Oil", "", "1 tablespoon"], ["Red Onions", "", "1 tablespoon chopped"], ["Garlic", "", "1 clove peeled crushed"], ["Salt", "", "To taste"], ["Pepper", "", "To taste"]] },
  { id: "aubergine-and-hummus-grills", mealId: "53278", name: "Aubergine & hummus grills", zh: "烤茄子鷹嘴豆泥", cat: "Vegetarian",
    ing: [["Aubergine", "", "2"], ["Vegetable Oil", "", "2 tablespoons"], ["Bread", "", "3 sliced thinly"], ["Hummus", "", "300g"], ["Walnuts", "", "100g"], ["Parsley", "", "40g"]] },
  { id: "aubergine-couscous-salad", mealId: "53267", name: "Aubergine couscous salad", zh: "茄子北非小米沙拉", cat: "Vegetarian",
    ing: [["Aubergine", "", "1 sliced"], ["Olive Oil", "", "3 tablespoons"], ["Couscous", "", "140g"], ["Vegetable Stock", "", "225g"], ["Cherry Tomatoes", "", "200g"], ["Mint", "", "Handful"]] },
  { id: "avocado-dip-with-new-potatoes", mealId: "53107", name: "Avocado dip with new potatoes", zh: "酪梨沾醬佐新馬鈴薯", cat: "Vegetarian",
    ing: [["Avocado", "", "3 Large"], ["Natural Yoghurt", "", "200g"], ["Lime", "", "Zest and juice of 1"], ["Lemon", "", "Juice of 1/2"], ["Baby New Potatoes", "", "1.25kg"], ["Olive Oil", "", "2 tablespoons"]] },
  { id: "baingan-bharta", mealId: "52807", name: "Baingan Bharta", zh: "印度烤茄泥", cat: "Vegetarian",
    ing: [["Aubergine", "", "1 large"], ["Onion", "", "½ cup"], ["Tomatoes", "", "1 cup"], ["Garlic", "", "6 cloves"], ["Green Chilli", "", "1"], ["Red Chilli Powder", "", "¼ teaspoon"]] },
  { id: "beetroot-and-red-cabbage-sauerkraut", mealId: "53307", name: "Beetroot & red cabbage sauerkraut", zh: "甜菜根紫高麗菜酸菜", cat: "Vegetarian",
    ing: [["Beetroot", "", "320g"], ["Red Cabbage", "", "450g"], ["Onion", "", "1 small"], ["Caraway Seed", "", "2 tsp"], ["Sea Salt", "", "1 tsp"]] },
  { id: "beetroot-latkes", mealId: "53313", name: "Beetroot latkes", zh: "甜菜根薯餅", cat: "Vegetarian",
    ing: [["Rapeseed Oil", "", "1 tablespoon"], ["Greek Yogurt", "", "4 tablespoons"], ["Mint", "", "1/2 bag"], ["Rocket", "", "150g"], ["Cherry Tomatoes", "", "130g"], ["Beetroot", "", "400g"]] },
  { id: "beetroot-soup-borscht", mealId: "53078", name: "Beetroot Soup (Borscht)", zh: "甜菜根羅宋湯", cat: "Vegetarian",
    ing: [["Beetroot", "", "3"], ["Olive Oil", "", "4 tbs"], ["Chicken Stock Cube", "", "1"], ["Water", "", "6 cups"], ["Potatoes", "", "3"], ["Cannellini Beans", "", "1 can"]] },
  { id: "black-beans-hotpot", mealId: "53536", name: "Black Beans Hotpot", zh: "黑豆鍋", cat: "Vegetarian",
    ing: [["Black Beans", "", "400g"], ["Onion", "", "1 large"], ["Green Pepper", "", "1"], ["Red Pepper", "", "1"], ["Celery", "", "1/3 cup"], ["Garlic", "", "4 Cloves Crushed"]] },
  { id: "antiguan-breakfast-chop-up-and-saltfish", mealId: "53430", name: "Antiguan Breakfast (Chop Up and ‘Saltfish’)", zh: "安提瓜早餐鹹魚燴菜", cat: "Breakfast",
    ing: [["Egg Plants", "", "4"], ["Callaloo", "", "8 oz"], ["Pumpkin", "", "1 lb"], ["Garlic", "", "3 cloves Chopped"], ["Onion", "", "1 Diced"], ["Butter", "", "2 oz"]] },
  { id: "bread-omelette", mealId: "53076", name: "Bread omelette", zh: "麵包歐姆蛋", cat: "Breakfast",
    ing: [["Bread", "", "2"], ["Egg", "", "2"], ["Salt", "", "0.5"]] },
  { id: "breakfast-potatoes", mealId: "52965", name: "Breakfast Potatoes", zh: "早餐馬鈴薯", cat: "Breakfast",
    ing: [["Potatoes", "", "3 Medium"], ["Olive Oil", "", "1 tbs"], ["Bacon", "", "2 strips"], ["Garlic Clove", "", "Minced"], ["Maple Syrup", "", "1 tbs"], ["Parsley", "", "Garnish"]] },
  { id: "dutch-poffertjes-mini-pancakes", mealId: "53379", name: "Dutch poffertjes (mini pancakes)", zh: "荷蘭迷你鬆餅", cat: "Breakfast",
    ing: [["Flour", "", "125g"], ["Buckwheat Flour", "", "125g"], ["Eggs", "", "2"], ["Butter", "", "1 knob"], ["Milk", "", "300ml"], ["Yeast", "", "10g"]] },
  { id: "english-breakfast", mealId: "52895", name: "English Breakfast", zh: "英式早餐", cat: "Breakfast",
    ing: [["Sausages", "", "2"], ["Bacon", "", "3"], ["Mushrooms", "", "2"], ["Tomatoes", "", "2"], ["Black Pudding", "", "1 Slice"], ["Eggs", "", "2"]] },
  { id: "flija-layered-pancake-crepe", mealId: "53413", name: "Flija Layered Pancake / Crepe", zh: "阿爾巴尼亞千層薄餅", cat: "Breakfast",
    ing: [["Flour", "", "1 kg"], ["Water", "", "1 L"], ["Salt", "", "1 tsp"], ["Melted Butter", "", "220g"], ["Vegetable Oil", "", "200ml"], ["Greek Yogurt", "", "5 tablespoons"]] },
  { id: "fruit-and-cream-cheese-breakfast-pastries", mealId: "52957", name: "Fruit and Cream Cheese Breakfast Pastries", zh: "水果奶油起司早餐酥", cat: "Breakfast",
    ing: [["Cream Cheese", "", "1 1/4 oz"], ["Sugar", "", "1 1/4 cup"], ["Vanilla Extract", "", "1 teaspoon"], ["Flour", "", ""], ["Puff Pastry", "", "2"], ["Strawberries", "", ""]] },
  { id: "full-english-breakfast", mealId: "52896", name: "Full English Breakfast", zh: "全套英式早餐", cat: "Breakfast",
    ing: [["Sausages", "", "4"], ["Bacon", "", "4"], ["Mushrooms", "", "4"], ["Tomatoes", "", "3"], ["Black Pudding", "", "2 sliced"], ["Eggs", "", "2"]] },
  { id: "grits", mealId: "53450", name: "Grits", zh: "玉米糊", cat: "Breakfast",
    ing: [["Grits", "", "1/4 cup"], ["Salt", "", "1 tsp"], ["Water", "", "1 cup"]] },
  { id: "home-made-mandazi", mealId: "52967", name: "Home-made Mandazi", zh: "自製曼達齊炸麵包", cat: "Breakfast",
    ing: [["Self-raising Flour", "", "750g"], ["Sugar", "", "6 tablespoons"], ["Eggs", "", "2"], ["Milk", "", "1 cup"]] },
  { id: "jamaican-curry-goat", mealId: "53354", name: "Jamaican Curry Goat", zh: "牙買加咖哩羊肉", cat: "Goat",
    ing: [["Goat Meat", "", "3 Lbs"], ["Jamaican Curry Powder", "", "2.5 tbsp"], ["Ground Ginger", "", "1/2 tsp"], ["All-purpose Seasoning", "", "1/2 tsp"], ["Allspice", "", "1/4 tsp"], ["Onion", "", "1 chopped"]] },
  { id: "mbuzi-choma-roasted-goat", mealId: "52968", name: "Mbuzi Choma (Roasted Goat)", zh: "東非烤羊肉", cat: "Goat",
    ing: [["Goat Meat", "", "1 kg"], ["Corn Flour", "", "1 kg"], ["Tomatoes", "", "2"], ["Salt", "", "Pinch"], ["Onion", "", "1"], ["Green Chilli", "", "1"]] },
];

export const STEPS: Record<string, { en: string[]; zh: string[] }> = {
  "garlic-broccoli": {
    en: ["Cut the broccoli into even florets.", "Fry the sliced garlic in oil over medium heat until pale gold.",
         "Add the broccoli and a splash of water; cover for 2 minutes.",
         "Uncover, raise the heat, and toss until the water has gone. Salt and serve."],
    zh: ["花椰菜切成大小一致的小朵。", "中火以油將蒜片煎至微金黃。",
         "下花椰菜與少許水，加蓋燜 2 分鐘。", "開蓋轉大火翻炒收乾，加鹽調味即可。"]
  },
  "beef-broccoli-egg": {
    en: ["Beat the eggs with a pinch of salt.", "Sear the marinated beef over high heat, then set aside.",
         "Stir-fry the broccoli with a splash of water until just tender.",
         "Pour in the eggs, let them set at the edges, then fold gently.",
         "Return the beef, season with soy sauce and sugar, and serve immediately."],
    zh: ["雞蛋加少許鹽打散。", "大火將醃好的牛肉煎香後盛起。", "花椰菜加少許水炒至熟脆。",
         "倒入蛋液，邊緣凝固後輕輕翻拌。", "牛肉回鍋，以醬油與糖調味，趁熱上桌。"]
  },
  "tomato-egg": {
    en: ["Cut the tomatoes into wedges; beat the eggs with a pinch of salt.",
         "Scramble the eggs in hot oil until just set, then lift out.",
         "Cook the tomatoes until they soften and release their juice.",
         "Season with sugar and salt, return the eggs, and toss briefly.",
         "Finish with the green onion and serve with rice."],
    zh: ["番茄切塊，雞蛋加少許鹽打散。", "熱油炒蛋至半凝固後盛起。", "下番茄炒至出汁軟化。",
         "以糖與鹽調味，蛋回鍋略拌。", "撒上青蔥，配飯食用。"]
  },
  "avocado-beef-bowl": {
    en: ["Cook the rice and keep it warm.", "Sear the sliced beef in a hot pan, seasoning with soy sauce.",
         "Slice the avocado thin and fan it over the rice.", "Lay the beef alongside and spoon over the pan juices.",
         "Top with torn nori and sesame seeds."],
    zh: ["白米煮熟保溫。", "熱鍋煎香牛肉片，以醬油調味。", "酪梨切薄片鋪在飯上。",
         "牛肉擺在一旁，淋上鍋中肉汁。", "撒上海苔碎與白芝麻。"]
  },
  "three-cup-chicken": {
    en: ["Brown the chicken skin-side down in sesame oil with the ginger.",
         "Add the garlic and cook until fragrant.",
         "Pour in equal parts soy sauce, rice wine and sesame oil; simmer until glossy.",
         "Reduce until the sauce clings to the chicken.",
         "Fold through the basil off the heat and serve in the hot pot."],
    zh: ["麻油下薑片，雞肉皮朝下煎至上色。", "加入蒜頭炒出香氣。",
         "倒入等量醬油、米酒與麻油，燒至醬色油亮。", "收汁至醬汁裹住雞肉。",
         "熄火拌入九層塔，連鍋上桌。"]
  }
};
