/* Generated by scripts/gen-icon-registry.mjs — run `node scripts/gen-icon-registry.mjs` after adding icons. */
import type { LucideIcon } from "lucide-react-native";
import ArrowRight from "lucide-react-native/icons/arrow-right";
import Bell from "lucide-react-native/icons/bell";
import BookOpen from "lucide-react-native/icons/book-open";
import Boxes from "lucide-react-native/icons/boxes";
import CalendarDays from "lucide-react-native/icons/calendar-days";
import CalendarPlus from "lucide-react-native/icons/calendar-plus";
import Camera from "lucide-react-native/icons/camera";
import ChartNoAxesColumn from "lucide-react-native/icons/chart-no-axes-column";
import Check from "lucide-react-native/icons/check";
import CheckCheck from "lucide-react-native/icons/check-check";
import ChefHat from "lucide-react-native/icons/chef-hat";
import ChevronDown from "lucide-react-native/icons/chevron-down";
import ChevronLeft from "lucide-react-native/icons/chevron-left";
import ChevronRight from "lucide-react-native/icons/chevron-right";
import Circle from "lucide-react-native/icons/circle";
import CircleAlert from "lucide-react-native/icons/circle-alert";
import CircleCheck from "lucide-react-native/icons/circle-check";
import Clock from "lucide-react-native/icons/clock";
import Cloud from "lucide-react-native/icons/cloud";
import CloudCheck from "lucide-react-native/icons/cloud-check";
import CloudRain from "lucide-react-native/icons/cloud-rain";
import CloudSun from "lucide-react-native/icons/cloud-sun";
import Columns2 from "lucide-react-native/icons/columns-2";
import CookingPot from "lucide-react-native/icons/cooking-pot";
import Copy from "lucide-react-native/icons/copy";
import Download from "lucide-react-native/icons/download";
import Eye from "lucide-react-native/icons/eye";
import Flame from "lucide-react-native/icons/flame";
import FlaskConical from "lucide-react-native/icons/flask-conical";
import Footprints from "lucide-react-native/icons/footprints";
import Gift from "lucide-react-native/icons/gift";
import Heart from "lucide-react-native/icons/heart";
import HeartPulse from "lucide-react-native/icons/heart-pulse";
import Hourglass from "lucide-react-native/icons/hourglass";
import House from "lucide-react-native/icons/house";
import Images from "lucide-react-native/icons/images";
import Link from "lucide-react-native/icons/link";
import List from "lucide-react-native/icons/list";
import ListChecks from "lucide-react-native/icons/list-checks";
import LoaderCircle from "lucide-react-native/icons/loader-circle";
import LockKeyhole from "lucide-react-native/icons/lock-keyhole";
import MapPin from "lucide-react-native/icons/map-pin";
import Maximize from "lucide-react-native/icons/maximize";
import Mic from "lucide-react-native/icons/mic";
import Minimize from "lucide-react-native/icons/minimize";
import Minus from "lucide-react-native/icons/minus";
import Monitor from "lucide-react-native/icons/monitor";
import Pause from "lucide-react-native/icons/pause";
import Pencil from "lucide-react-native/icons/pencil";
import Play from "lucide-react-native/icons/play";
import Plus from "lucide-react-native/icons/plus";
import RefreshCw from "lucide-react-native/icons/refresh-cw";
import RotateCcw from "lucide-react-native/icons/rotate-ccw";
import Section from "lucide-react-native/icons/section";
import Send from "lucide-react-native/icons/send";
import ServerCog from "lucide-react-native/icons/server-cog";
import Settings from "lucide-react-native/icons/settings";
import Share2 from "lucide-react-native/icons/share-2";
import ShieldAlert from "lucide-react-native/icons/shield-alert";
import ShieldPlus from "lucide-react-native/icons/shield-plus";
import ShoppingCart from "lucide-react-native/icons/shopping-cart";
import Smartphone from "lucide-react-native/icons/smartphone";
import Snowflake from "lucide-react-native/icons/snowflake";
import Sparkles from "lucide-react-native/icons/sparkles";
import Star from "lucide-react-native/icons/star";
import Sun from "lucide-react-native/icons/sun";
import Tablet from "lucide-react-native/icons/tablet";
import ThumbsUp from "lucide-react-native/icons/thumbs-up";
import Timer from "lucide-react-native/icons/timer";
import Trash from "lucide-react-native/icons/trash";
import Trophy from "lucide-react-native/icons/trophy";
import Upload from "lucide-react-native/icons/upload";
import User from "lucide-react-native/icons/user";
import UserCog from "lucide-react-native/icons/user-cog";
import UserRound from "lucide-react-native/icons/user-round";
import Users from "lucide-react-native/icons/users";
import Utensils from "lucide-react-native/icons/utensils";
import WandSparkles from "lucide-react-native/icons/wand-sparkles";
import Watch from "lucide-react-native/icons/watch";
import Wifi from "lucide-react-native/icons/wifi";
import WifiOff from "lucide-react-native/icons/wifi-off";
import X from "lucide-react-native/icons/x";

export const ICONS: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  "bell": Bell,
  "book-open": BookOpen,
  "boxes": Boxes,
  "calendar-days": CalendarDays,
  "calendar-plus": CalendarPlus,
  "camera": Camera,
  "chart-no-axes-column": ChartNoAxesColumn,
  "check": Check,
  "check-check": CheckCheck,
  "chef-hat": ChefHat,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle": Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "clock": Clock,
  "cloud": Cloud,
  "cloud-check": CloudCheck,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  "columns-2": Columns2,
  "cooking-pot": CookingPot,
  "copy": Copy,
  "download": Download,
  "eye": Eye,
  "flame": Flame,
  "flask-conical": FlaskConical,
  "footprints": Footprints,
  "gift": Gift,
  "heart": Heart,
  "heart-pulse": HeartPulse,
  "hourglass": Hourglass,
  "house": House,
  "images": Images,
  "link": Link,
  "list": List,
  "list-checks": ListChecks,
  "loader-circle": LoaderCircle,
  "lock-keyhole": LockKeyhole,
  "map-pin": MapPin,
  "maximize": Maximize,
  "mic": Mic,
  "minimize": Minimize,
  "minus": Minus,
  "monitor": Monitor,
  "pause": Pause,
  "pencil": Pencil,
  "play": Play,
  "plus": Plus,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "section": Section,
  "send": Send,
  "server-cog": ServerCog,
  "settings": Settings,
  "share-2": Share2,
  "shield-alert": ShieldAlert,
  "shield-plus": ShieldPlus,
  "shopping-cart": ShoppingCart,
  "smartphone": Smartphone,
  "snowflake": Snowflake,
  "sparkles": Sparkles,
  "star": Star,
  "sun": Sun,
  "tablet": Tablet,
  "thumbs-up": ThumbsUp,
  "timer": Timer,
  "trash": Trash,
  "trophy": Trophy,
  "upload": Upload,
  "user": User,
  "user-cog": UserCog,
  "user-round": UserRound,
  "users": Users,
  "utensils": Utensils,
  "wand-sparkles": WandSparkles,
  "watch": Watch,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "x": X,
};
